name: EP-daily-task


on:
  
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '8 0 * * *' 
    # cron表达式，时区是UTC时间，比我们早8小时，要用我们的时间减去8小时后填上去，如上所表示的是每天23点5分
    # 建议每个人都修改下时间！不要使用默认时间！最好不要设定在整点，错开峰值，避免大量G站同一个IP在相同时间去请求B站接口，导致IP被禁！
    

jobs:
  run-EP-tool:

    runs-on: ubuntu-latest

    steps:

    # 输出服务器的IP
    #- name: IP
    #  run: sudo curl ifconfig.me

    # 设置服务器时区为东八区 
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    # 检出，就是官方社区贡献的用来拉取仓库分支的 Action，你不需要考虑安装 git 命令工具，只需要把分支参数传入即可。
    - name: Checkout
      uses: actions/checkout@v2

    # Python 环境
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install requests json
    #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # 运行
    #- name: Run APP
    #  run: |
    #    python text.py

    # 安装脚本所需的依赖
    - name: Install requests
      run: pip install requests
      # 运行脚本
    - name: 'Working'
      env:	#添加环境变量
        SCKEY: ${{ secrets.PUSHPLUSSCKEY }}
        SCKEY: ${{ secrets.SCKEY }}
        SKEY: ${{ secrets.SKEY }}
      run: python weater.py
   
